version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    privileged: true
    # FIX PER FEDORA: Limitiamo i file aperti per evitare il crash di Java
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - ./hddata:/submit:z
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    links:
      - namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:9870

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    links:
      - namenode
      - datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    privileged: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./hddata:/submit:z
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
